// ScanOnUpdate.js
// Version: 0.0.1
// Event: On Awake
// Description: Create a basic scan example with calling the scan module on update

//@input Component.Text scanResult
//@input string scanType = "Objects" {"values": [{"value": "Objects", "label": "Objects"}, {"value": "Cars", "label": "Cars"}, {"value": "Dogs", "label": "Dogs"}, {"value": "Places", "label": "Places"}], "widget": "combobox"}
//@input Component.Text scanTypeText
//@input bool printDebugLog
//@input Component.Text instruction

//@input SceneObject blob

//@input SceneObject blur




initialize();

function initialize() {
    global.lastTime = getTime();

    if (script.scanTypeText) {
        script.scanTypeText.text = script.scanType;
    }
    
    if (!script.scanResult) {
        debugPrint("ERROR! No Scan Result Text input, please link a text component to the scanResult variable.");
        return false;
    }
    
//    scan();
//
    return true;
    
}



function debugPrint(message) {
    if (script.printDebugLog) {
        print(message);
    }
}

var scanReady = true;
global.isShowing = false;

script.createEvent("TapEvent").bind(function() {
    
    global.lastTime = getTime();

    script.instruction.text = ""
    
    //only call scan if enough time has passed since getting last result
    if (!scanReady) {
        return;
    }    

    script.scanResult.text = "";
    scanReady = false;
    
    function scanOther() {
         global.getScanResults("Places", function callback(data) {
        
        if (!data) {
            script.scanResult.text = "";
            scanReady = true;
            global.tweenManager.startTween(script.blob, "blobHide");
                global.tweenManager.startTween(script.blur, "blurOut");
            global.isShowing = false;
            
            return;
        }
        
        var combinedResults = data[0].name;
        if (data.length > 1) {
            for (var i=1;i<data.length;i++) {
                combinedResults += "\n";
                combinedResults += data[i].name;
            }
            
        }
            
         var syns = synonyms[data[Math.floor(Math.random()*data.length)].name];
        var word = data[Math.floor(Math.random()*data.length)].name;
        if(syns){
            word = syns[Math.floor(Math.random()*syns.length)]

        }
        script.scanResult.text = "What if the imagination of this " + word + " could be " + ENDINGS[Math.floor(Math.random()*ENDINGS.length)] + "?";
                
//        script.scanResult.text = "What if the imagination of this " + data[Math.floor(Math.random()*data.length)].name + " could be " + ENDINGS[Math.floor(Math.random()*ENDINGS.length)] + "?";
         if(!global.isShowing){
            global.tweenManager.startTween(script.blob, "blobTween");
            global.tweenManager.startTween(script.blur, "blurIn");
            global.isShowing = true;
         } else {
                            global.tweenManager.startTween(script.blob, "blobChange");

            }     
            global.isShowing = true;

        scanReady = true;
    }, function failureCallback() {
        scanReady = true;
    }); 
        
    }
    
    global.getScanResults(script.scanType, function callback(data) {
        
        if (!data) {
            script.scanResult.text = "";
            scanReady = true;
            
            scanOther();
            
            return;
        }
        
        var combinedResults = data[0].name;
        if (data.length > 1) {
            for (var i=1;i<data.length;i++) {
                combinedResults += "\n";
                combinedResults += data[i].name;
            }
            
        }
        var syns = synonyms[data[Math.floor(Math.random()*data.length)].name];
        var word = data[Math.floor(Math.random()*data.length)].name;
        if(syns){
            word = syns[Math.floor(Math.random()*syns.length)]

        }
        script.scanResult.text = "What if the imagination of this " + word + " could be " + ENDINGS[Math.floor(Math.random()*ENDINGS.length)] + "?";
                
        
        if(!global.isShowing){
            global.tweenManager.startTween(script.blob, "blobTween");
            global.tweenManager.startTween(script.blur, "blurIn");
            global.isShowing = true;
        } else {
                        global.tweenManager.startTween(script.blob, "blobChange");

        }
        scanReady = true;
    }, function failureCallback() {
        scanReady = true;
    });
    
});

var ENDINGS = ENDINGS = ['a disease',
'a gestalt',
'a methodology',
'a design term',
'a campaign',
'a government',
'a plant type',
'a species',
'a bacteria',
'a virus',
'a cult',
'an apocalypse',
'a new order',
'a rule',
'a law',
'a regulation',
'a nation',
'a city',
'a zoning law',
'a new beginning',
'a film',
'a novel',
'a misleading myth',
'a Black hole',
'a game',
'a toy',
'an algorithm',
'a manual',
'a map',
'a notebook',
'a writing tool',
'a tool',
'a device',
'a doll',
'a mantra',
'a song title',
'a sculpture',
'a new aesthetic',
'a geographic region',
'a working title',
'a business team',
'a think tank',
'a new word',
'a new world',
'a spaceship',
'a model',
'a nation-state',
'an engineer',
'a scientific tool',
'a new discovery',
'a planet',
'a rule of physics',
'a protopia',
'a mental health disorder',
'a restorative design',
'an oxymoron',
'a quasi-object',
'an asset against opaque systems',
'rhizomatic',
'a biopolitical device',
'a conspiracy theory',
'a social innovation',
'a hysterical bomb',
'a transhumanist utopia',
'a possibility for our political impotence',
'a computational God',
'a political scandal',
'a way to improve our sensibility',
'a help to our consciousness',
'a breathing exercise',
'a new environmental aesthetics',
'a way to prevent our extinction',
'a critical reflection',
'a place of hope',
'a resilient gender politics',
'an investigative research',
'a design for a public space',
'a pornographic content',
'a subconscious urge',
'a form of birth control',
'a mistaken identity',
'an emergent strategy',
'a procedural game',
'part of our political fabric',
'part of an impossible conversation',
'part of a learning adaptation',
'a temporary shelter',
'an emotional lockdown',
'a vulnerable reflection',
'a virtuous cycle',
'a liberated relationship',
'a healing ritual',
'an emergent process',
'a rebellious dream',
'an intellectual toolbox',
'a planetary indigestion',
'an unintentional pathway',
'a recombinant dilemma',
'an artificial breathing',
'a gatekeeper of desires',
'a creature of the Anthropocene',
'a crisis of conscience',
'a droplet of hallucination',
'a dictatorship of transparency',
'a broken intimacy',
'a gamified anxiety',
'an obsolete algorithm',
'a sentimental education',
'an empathy bomb',
'part of a new revelation',
'a morning epiphany',
'a recovery for cynicism'
]


var synonyms = {
    "Accordion": ["Accordion", "accordion", "piano accordion", "squeeze box"],
    "Adhesive tape": ["Adhesive tape"],
    "Airplane": ["Airplane", "airplane", "aeroplane", "plane"],
    "Alarm clock": ["Alarm clock"],
    "Alpaca": ["Alpaca", "alpaca", "Lama pacos"],
    "Ambulance": ["Ambulance", "ambulance"],
    "Ant": ["Ant", "ant", "emmet", "pismire"],
    "Antelope": ["Antelope", "antelope"],
    "Apple": ["Apple", "apple", "orchard apple tree", "Malus pumila"],
    "Arm": ["Arm", "arm", "branch", "limb", "weapon", "weapon system", "subdivision", "sleeve", "build up", "fortify", "gird"],
    "Armadillo": ["Armadillo", "armadillo"],
    "Artichoke": ["Artichoke", "artichoke", "globe artichoke", "artichoke plant", "Cynara scolymus"],
    "Backpack": ["Backpack", "backpack", "back pack", "knapsack", "packsack", "rucksack", "haversack", "pack"],
    "Bagel": ["Bagel", "bagel", "beigel"],
    "Balance beam": ["Balance beam"],
    "Ball": ["Ball", "ball", "musket ball", "globe", "orb", "testis", "testicle", "orchis", "ballock", "bollock", "nut", "egg", "Lucille Ball", "clod", "glob", "lump", "clump", "chunk", "formal"],
    "Balloon": ["Balloon", "balloon", "inflate", "billow"],
    "Banana": ["Banana", "banana", "banana tree"],
    "Banjo": ["Banjo", "banjo"],
    "Barge": ["Barge", "barge", "flatboat", "hoy", "lighter", "thrust ahead", "push forward"],
    "Barrel": ["Barrel", "barrel", "gun barrel", "cask", "drum", "barrelful", "bbl"],
    "Baseball bat": ["Baseball bat"],
    "Baseball glove": ["Baseball glove"],
    "Bat (Animal)": ["Bat (Animal)"],
    "Bathroom cabinet": ["Bathroom cabinet"],
    "Bathtub": ["Bathtub", "bathtub", "bathing tub", "bath", "tub"],
    "Beaker": ["Beaker", "beaker"],
    "Bear": ["Bear", "bear", "give birth", "deliver", "birth", "have", "digest", "endure", "stick out", "stomach", "stand", "tolerate", "support", "brook", "abide", "suffer", "put up", "turn out", "take over", "accept", "assume", "hold", "carry", "contain", "yield", "pay", "wear", "behave", "acquit", "deport", "conduct", "comport", "have a bun in the oven", "gestate", "expect"],
    "Bed": ["Bed", "bed", "bottom", "seam", "layer", "sleep together", "roll in the hay", "love", "make out", "make love", "sleep with", "get laid", "have sex", "know", "do it", "be intimate", "have intercourse", "have it away", "have it off", "screw", "fuck", "jazz", "eff", "hump", "lie with", "have a go at it", "bang", "get it on", "bonk", "go to bed", "turn in", "crawl in", "kip down", "hit the hay", "hit the sack", "sack out", "go to sleep", "retire"],
    "Bee": ["Bee", "bee"],
    "Beehive\fBeetle": ["Beehive\fBeetle"],
    "Bell pepper": ["Bell pepper"],
    "Belt": ["Belt", "belt", "knock", "bash", "bang", "smash", "swath", "belt ammunition", "belted ammunition", "rap", "whack", "whang", "belt out"],
    "Bench": ["Bench", "bench", "terrace", "judiciary", "workbench", "work bench"],
    "Bicycle": ["Bicycle", "bicycle", "bike", "wheel", "cycle", "pedal"],
    "Bicycle helmet": ["Bicycle helmet"],
    "Billboard": ["Billboard", "billboard", "hoarding"],
    "Billiard table": ["Billiard table"],
    "Binoculars": ["Binoculars", "binoculars", "field glasses", "opera glasses"],
    "Bird": ["Bird", "bird", "fowl", "dame", "doll", "wench", "skirt", "chick", "boo", "hoot", "Bronx cheer", "hiss", "raspberry", "razzing", "razz", "snort", "shuttlecock", "birdie", "shuttle", "birdwatch"],
    "Blender": ["Blender", "blender", "liquidizer", "liquidiser"],
    "Blue jay": ["Blue jay"],
    "Boat": ["Boat", "boat", "gravy boat", "gravy holder", "sauceboat"],
    "Body": ["Body", "body", "organic structure", "physical structure", "dead body", "torso", "trunk", "consistency", "consistence", "eubstance", "soundbox", "personify"],
    "Book": ["Book", "book", "volume", "record", "record book", "script", "playscript", "ledger", "leger", "account book", "book of account", "rule book", "Koran", "Quran", "al-Qur'an", "Bible", "Christian Bible", "Good Book", "Holy Scripture", "Holy Writ", "Scripture", "Word of God", "Word", "reserve", "hold"],
    "Bookcase": ["Bookcase", "bookcase"],
    "Boot": ["Boot", "boot", "bang", "charge", "rush", "flush", "thrill", "kick", "the boot", "iron boot", "iron heel", "kicking", "reboot", "bring up"],
    "Bottle": ["Bottle", "bottle", "bottleful", "feeding bottle", "nursing bottle"],
    "Bowl": ["Bowl", "bowl", "trough", "bowlful", "stadium", "arena", "sports stadium", "bowling ball", "pipe bowl", "roll"],
    "Bowling equipment": ["Bowling equipment"],
    "Box": ["Box", "box", "loge", "boxful", "corner", "boxwood", "box seat", "package"],
    "Bread": ["Bread", "bread", "breadstuff", "staff of life", "boodle", "cabbage", "clams", "dinero", "dough", "gelt", "kale", "lettuce", "lolly", "lucre", "loot", "moolah", "pelf", "scratch", "shekels", "simoleons", "sugar", "wampum"],
    "Briefcase": ["Briefcase", "briefcase"],
    "Broccoli": ["Broccoli", "broccoli", "Brassica oleracea italica"],
    "Bronze sculpture": ["Bronze sculpture"],
    "Brown bear": ["Brown bear"],
    "Bull": ["Bull", "bull", "bruiser", "strapper", "Samson", "bullshit", "Irish bull", "horseshit", "shit", "crap", "dogshit", "cop", "copper", "fuzz", "pig", "Taurus", "Taurus the Bull", "bull's eye", "papal bull", "bull through", "talk through one's hat", "fake"],
    "Burrito": ["Burrito", "burrito"],
    "Bus": ["Bus", "bus", "autobus", "coach", "charabanc", "double-decker", "jitney", "motorbus", "motorcoach", "omnibus", "passenger vehicle", "bus topology", "busbar", "jalopy", "heap"],
    "Bust": ["Bust", "flop", "bust", "fizzle", "female chest", "tear", "binge", "bout", "break", "raid", "rupture", "snap", "wear", "wear out", "fall apart", "burst", "broke", "skint", "stone-broke", "stony-broke"],
    "Butterfly": ["Butterfly", "butterfly", "butterfly stroke", "chat up", "flirt", "dally", "coquet", "coquette", "romance", "philander", "mash"],
    "Cabbage": ["Cabbage", "cabbage", "chou", "boodle", "bread", "clams", "dinero", "dough", "gelt", "kale", "lettuce", "lolly", "lucre", "loot", "moolah", "pelf", "scratch", "shekels", "simoleons", "sugar", "wampum", "cultivated cabbage", "Brassica oleracea", "pilfer", "purloin", "pinch", "abstract", "snarf", "swipe", "hook", "sneak", "filch", "nobble", "lift"],
    "Cabinetry": ["Cabinetry", "cabinetwork", "cabinetry"],
    "Cake": ["Cake", "cake", "bar", "patty", "coat"],
    "Cake stand\fCalculator": ["Cake stand\fCalculator"],
    "Camel": ["Camel", "camel"],
    "Camera": ["Camera", "camera", "photographic camera", "television camera", "tv camera"],
    "Can opener": ["Can opener"],
    "Canary": ["Canary", "fink", "snitch", "snitcher", "stoolpigeon", "stool pigeon", "stoolie", "sneak", "sneaker", "canary", "canary yellow", "canary bird", "canary-yellow"],
    "Candle": ["Candle", "candle", "taper", "wax light", "candela", "cd", "standard candle"],
    "Candy": ["Candy", "candy", "confect", "sugarcoat", "glaze"],
    "Canoe": ["Canoe", "canoe"],
    "Cantaloupe": ["Cantaloupe", "cantaloupe", "cantaloup", "cantaloupe vine", "cantaloup vine", "Cucumis melo cantalupensis"],
    "Car": ["Car", "car", "auto", "automobile", "machine", "motorcar", "railcar", "railway car", "railroad car", "gondola", "elevator car", "cable car"],
    "Carrot": ["Carrot", "carrot", "cultivated carrot", "Daucus carota sativa"],
    "Cart": ["Cart", "cart", "handcart", "pushcart", "go-cart", "haul", "hale", "drag"],
    "Cassette deck": ["Cassette deck"],
    "Castle": ["Castle", "palace", "castle", "rook", "castling"],
    "Cat": ["Cat", "cat", "true cat", "guy", "hombre", "bozo", "kat", "khat", "qat", "quat", "Arabian tea", "African tea", "cat-o'-nine-tails", "Caterpillar", "big cat", "computerized tomography", "computed tomography", "CT", "computerized axial tomography", "computed axial tomography", "CAT", "vomit", "vomit up", "purge", "cast", "sick", "be sick", "disgorge", "regorge", "retch", "puke", "barf", "spew", "spue", "chuck", "upchuck", "honk", "regurgitate", "throw up"],
    "Cat furniture": ["Cat furniture"],
    "Caterpillar": ["Caterpillar", "caterpillar", "cat"],
    "Cattle": ["Cattle", "cattle", "cows", "kine", "oxen", "Bos taurus"],
    "Ceiling fan": ["Ceiling fan"],
    "Cello": ["Cello", "cello", "violoncello"],
    "Centipede": ["Centipede", "centipede"],
    "Chainsaw": ["Chainsaw", "chain saw", "chainsaw"],
    "Chair": ["Chair", "chair", "professorship", "president", "chairman", "chairwoman", "chairperson", "electric chair", "death chair", "hot seat", "moderate", "lead"],
    "Cheese": ["Cheese", "cheese", "tall mallow", "high mallow", "cheeseflower", "Malva sylvestris"],
    "Cheetah": ["Cheetah", "cheetah", "chetah", "Acinonyx jubatus"],
    "Chest of drawers": ["Chest of drawers"],
    "Chicken": ["Chicken", "chicken", "poulet", "volaille", "Gallus gallus", "wimp", "crybaby", "chickenhearted", "lily-livered", "white-livered", "yellow", "yellow-bellied"],
    "Chime": ["Chime", "chime", "bell", "gong"],
    "Chisel": ["Chisel", "chisel", "cheat", "rip off"],
    "Chopsticks": ["Chopsticks", "chopstick"],
    "Christmas tree": ["Christmas tree"],
    "Clock": ["Clock", "clock", "time"],
    "Closet": ["Closet", "cupboard", "closet", "water closet", "W.C.", "loo", "wardrobe", "press"],
    "Clothing": ["Clothing", "clothing", "article of clothing",  "wearable", "dress", "clothe", "enclothed one", "garb", "raiment", "toga", "garment", "apparel", "weirdo", "adornment", "cloak", "drape", "robe"],
    "Coat\fCocktail": ["Coat\fCocktail"],
    "Coconut": ["Coconut", "coconut", "coconut meat", "cocoanut", "coconut palm", "coco palm", "coco", "cocoa palm", "coconut tree", "Cocos nucifera"],
    "Coffee": ["Coffee", "coffee", "java", "coffee tree", "coffee bean", "coffee berry", "chocolate", "deep brown", "umber", "burnt umber"],
    "Coffee cup": ["Coffee cup"],
    "Coffee table": ["Coffee table"],
    "Coffeemaker": ["Coffeemaker"],
    "Coin": ["Coin", "coin", "mint", "strike"],
    "Common fig": ["Common fig"],
    "Common sunflower": ["Common sunflower"],
    "Computer keyboard": ["Computer keyboard"],
    "Computer monitor": ["Computer monitor"],
    "Computer mouse": ["Computer mouse"],
    "Convenience store": ["Convenience store"],
    "Cookie": ["Cookie", "cookie", "cooky", "biscuit"],
    "Cooking spray": ["Cooking spray"],
    "Corded phone": ["Corded phone"],
    "Couch": ["Couch", "sofa", "couch", "lounge", "frame", "redact", "cast", "put"],
    "Countertop": ["Countertop", "countertop"],
    "Cowboy hat": ["Cowboy hat"],
    "Crab": ["Crab", "crab", "crabby person", "Cancer", "Cancer the Crab", "crabmeat", "crab louse", "pubic louse", "Phthirius pubis", "gripe", "bitch", "grouse", "beef", "squawk", "bellyache", "holler"],
    "Cream": ["Cream", "cream", "pick", "ointment", "emollient", "bat", "clobber", "drub", "thrash", "lick", "skim", "skim off", "cream off"],
    "Cricket ball": ["Cricket ball"],
    "Crocodile": ["Crocodile", "crocodile"],
    "Croissant": ["Croissant", "crescent roll", "croissant"],
    "Crown": ["Crown", "crown", "diadem", "treetop", "peak", "crest", "top", "tip", "summit", "pennant", "pate", "poll", "crownwork", "jacket", "jacket crown", "cap", "coronate"],
    "Cucumber": ["Cucumber", "cucumber", "cucumber vine", "Cucumis sativus", "cuke"],
    "Cupboard": ["Cupboard", "cupboard", "closet"],
    "Curtain": ["Curtain", "curtain", "drape", "drapery", "mantle", "pall"],
    "Cutting board": ["Cutting board"],
    "Deer": ["Deer", "deer", "cervid"],
    "Desk": ["Desk", "desk"],
    "Diaper": ["Diaper", "diaper", "nappy", "napkin"],
    "Dice": ["Dice", "die", "dice", "cube"],
    "Digital clock": ["Digital clock"],
    "Dinosaur\fDishwasher": ["Dinosaur\fDishwasher"],
    "Dog": ["Dog", "dog", "domestic dog", "Canis familiaris", "frump", "cad", "bounder", "blackguard", "hound", "heel", "frank", "frankfurter", "hotdog", "hot dog", "wiener", "wienerwurst", "weenie", "pawl", "detent", "click", "andiron", "firedog", "dog-iron", "chase", "chase after", "trail", "tail", "tag", "give chase", "go after", "track"],
    "Dog bed": ["Dog bed"],
    "Doll": ["Doll", "doll", "dolly", "dame", "wench", "skirt", "chick", "bird"],
    "Dolphin": ["Dolphin", "dolphinfish", "dolphin", "mahimahi"],
    "Door": ["Door", "door", "doorway", "room access", "threshold"],
    "Door handle": ["Door handle"],
    "Doughnut": ["Doughnut", "ring", "halo", "annulus", "doughnut", "anchor ring", "donut", "sinker"],
    "Dragonfly": ["Dragonfly", "dragonfly", "darning needle", "devil's darning needle", "sewing needle", "snake feeder", "snake doctor", "mosquito hawk", "skeeter hawk"],
    "Drawer": ["Drawer", "drawer", "draftsman"],
    "Dress": ["Dress", "dress", "frock", "attire", "garb", "apparel", "wearing apparel", "clothes", "get dressed", "clothe", "enclothe", "raiment", "tog", "garment", "habilitate", "fit out", "dress up", "preen", "primp", "plume", "dress out", "line up", "trim", "garnish", "decorate", "snip", "clip", "crop", "lop", "prune", "cut back", "groom", "curry", "arrange", "set", "do", "coif", "coiffe", "coiffure", "full-dress"],
    "Drill (Tool)": ["Drill (Tool)"],
    "Drink": ["Drink", "drink", "drinking", "boozing", "drunkenness", "crapulence", "beverage", "drinkable", "potable", "swallow", "deglutition", "imbibe", "booze", "fuddle", "toast", "pledge", "salute", "wassail", "drink in", "tope"],
    "Drinking straw": ["Drinking straw"],
    "Drum": ["Drum", "drum", "membranophone", "tympan", "barrel", "metal drum", "brake drum", "drumfish", "beat", "thrum", "cram", "grind away", "bone up", "swot", "get up", "mug up", "swot up", "bone"],
    "Duck": ["Duck", "duck", "duck's egg", "dip", "douse", "hedge", "fudge", "evade", "put off", "circumvent", "parry", "elude", "skirt", "dodge", "sidestep"],
    "Dumbbell": ["Dumbbell", "dumbbell", "dummy", "dope", "boob", "booby", "pinhead"],
    "Eagle": ["Eagle", "eagle", "bird of Jove", "double birdie"],
    "Earrings": ["Earrings", "earring"],
    "Egg (Food)": ["Egg (Food)"],
    "Elephant": ["Elephant", "elephant"],
    "Envelope": ["Envelope", "envelope", "gasbag"],
    "Eraser": ["Eraser", "eraser"],
    "Facial tissue holder": ["Facial tissue holder"],
    "Falcon": ["Falcon", "falcon"],
    "Fast food": ["Fast food"],
    "Fax": ["Fax", "facsimile", "facsimile machine", "fax", "telefax"],
    "Fedora": ["Fedora", "fedora", "felt hat", "homburg", "Stetson", "trilby"],
    "Filing cabinet": ["Filing cabinet"],
    "Fire hydrant": ["Fire hydrant"],
    "Fireplace": ["Fireplace", "fireplace", "hearth", "open fireplace"],
    "Fish": ["Fish", "fish", "Pisces", "Pisces the Fishes", "angle"],
    "Flag": ["Flag", "flag", "masthead", "iris", "fleur-de-lis", "sword lily", "signal flag", "pin", "flagstone", "sag", "droop", "swag", "ease up", "ease off", "slacken off"],
    "Flashlight": ["Flashlight", "flashlight", "torch"],
    "Flower\fFlowerpot": ["Flower\fFlowerpot"],
    "Flute": ["Flute", "flute", "transverse flute", "flute glass", "champagne flute", "fluting"],
    "Flying disc": ["Flying disc"],
    "Food processor": ["Food processor"],
    "Foot": ["Foot", "foot", "human foot", "pes", "ft", "animal foot", "foundation", "base", "fundament", "groundwork", "substructure", "understructure", "invertebrate foot", "infantry", "metrical foot", "metrical unit", "pick", "leg it", "hoof", "hoof it", "foot up"],
    "Football": ["Football", "football", "football game"],
    "Football helmet": ["Football helmet"],
    "Footwear": ["Footwear", "footwear", "footgear"],
    "Fork": ["Fork", "fork", "branching", "ramification", "forking", "crotch", "pitchfork", "branch", "ramify", "furcate", "separate"],
    "Fountain": ["Fountain", "fountain", "spring", "outflow", "outpouring", "natural spring", "jet", "fount"],
    "Fox": ["Fox", "fox", "dodger", "slyboots", "Charles James Fox", "George Fox", "flim-flam", "play a joke on", "play tricks", "trick", "fob", "pull a fast one on", "play a trick on", "confuse", "throw", "befuddle", "fuddle", "bedevil", "confound", "discombobulate"],
    "French fries": ["French fries"],
    "French horn": ["French horn"],
    "Frog": ["Frog", "frog", "toad", "toad frog", "anuran", "batrachian", "salientian", "Gaul"],
    "Fruit": ["Fruit", "fruit", "yield"],
    "Frying pan": ["Frying pan"],
    "Furniture": ["Furniture", "furniture", "piece of furniture", "article of furniture"],
    "Garden Asparagus": ["Garden Asparagus"],
    "Gas stove": ["Gas stove"],
    "Giraffe": ["Giraffe", "giraffe", "camelopard", "Giraffa camelopardalis"],
    "Glasses": ["Glasses", "spectacles", "specs", "eyeglasses", "glasses", "glass", "drinking glass", "glassful", "field glass", "spyglass", "methamphetamine", "methamphetamine hydrochloride", "Methedrine", "meth", "deoxyephedrine", "chalk", "chicken feed", "crank", "ice", "shabu", "trash", "looking glass", "glaze", "glass in", "glass over", "glaze over"],
    "Glove": ["Glove", "baseball glove", "glove", "baseball mitt", "mitt", "boxing glove"],
    "Goat": ["Goat", "goat", "caprine animal", "butt", "laughingstock", "stooge", "Capricorn", "Capricorn the Goat"],
    "Goggles": ["Goggles", "goggles", "goggle", "gape", "gawp", "gawk"],
    "Goldfish": ["Goldfish", "goldfish", "Carassius auratus"],
    "Golf ball": ["Golf ball"],
    "Golf cart": ["Golf cart"],
    "Gondola": ["Gondola", "gondola car", "gondola", "car"],
    "Goose": ["Goose", "goose", "fathead", "goof", "goofball", "bozo", "jackass", "cuckoo", "twat", "zany"],
    "Grape": ["Grape", "grape", "grapevine", "grape vine", "grapeshot"],
    "Grapefruit": ["Grapefruit", "grapefruit", "Citrus paradisi"],
    "Grinder": ["Grinder", "bomber", "grinder", "hero", "hero sandwich", "hoagie", "hoagy", "Cuban sandwich", "Italian sandwich", "poor boy", "sub", "submarine", "submarine sandwich", "torpedo", "wedge", "zep", "molar", "mill", "milling machinery"],
    "Guacamole": ["Guacamole", "guacamole"],
    "Guitar": ["Guitar", "guitar"],
    "Hair dryer\fHair spray": ["Hair dryer\fHair spray"],
    "Hamburger": ["Hamburger", "hamburger", "beefburger", "burger", "ground beef"],
    "Hammer": ["Hammer", "hammer", "cock", "malleus", "mallet", "power hammer", "pound", "hammering", "pounding", "forge"],
    "Hamster": ["Hamster", "hamster"],
    "Hand": ["Hand", "hand", "manus", "mitt", "paw", "hired hand", "hired man", "handwriting", "script", "deal", "bridge player", "helping hand", "pass", "reach", "pass on", "turn over", "give"],
    "Hand dryer": ["Hand dryer"],
    "Handbag": ["Handbag", "bag", "handbag", "pocketbook", "purse"],
    "Harmonica": ["Harmonica", "harmonica", "mouth organ", "harp", "mouth harp"],
    "Harp": ["Harp", "harp", "harmonica", "mouth organ", "mouth harp", "dwell"],
    "Harpsichord": ["Harpsichord", "harpsichord", "cembalo"],
    "Hat": ["Hat", "hat", "chapeau", "lid"],
    "Headphones": ["Headphones", "earphone", "earpiece", "headphone", "phone"],
    "Heater": ["Heater", "heater", "warmer", "fastball", "smoke", "hummer", "bullet"],
    "Hedgehog": ["Hedgehog", "porcupine", "hedgehog", "Erinaceus europaeus", "Erinaceus europeaeus"],
    "Helicopter": ["Helicopter", "helicopter", "chopper", "whirlybird", "eggbeater"],
    "Helmet": ["Helmet", "helmet"],
    "High heels": ["High heels"],
    "Hiking equipment": ["Hiking equipment"],
    "Hippopotamus": ["Hippopotamus", "hippopotamus", "hippo", "river horse", "Hippopotamus amphibius"],
    "Honeycomb": ["Honeycomb", "honeycomb"],
    "Horizontal bar": ["Horizontal bar"],
    "Horse": ["Horse", "horse", "Equus caballus", "gymnastic horse", "cavalry", "horse cavalry", "sawhorse", "sawbuck", "buck", "knight"],
    "Hot dog": ["Hot dog"],
    "House": ["House", "house", "firm", "business firm", "sign of the zodiac", "star sign", "sign", "mansion", "planetary house", "family", "household", "home", "menage", "theater", "theatre", "put up", "domiciliate"],
    "Houseplant": ["Houseplant", "houseplant"],
    "Humidifier": ["Humidifier"],
    "Ice cream": ["Ice cream"],
    "Indoor rower": ["Indoor rower"],
    "Infant bed": ["Infant bed"],
    "Insect": ["Insect", "insect", "worm", "louse", "dirt ball"],
    "Isopod": ["Isopod", "isopod"],
    "Jacket": ["Jacket", "jacket", "crown", "crownwork", "jacket crown", "cap"],
    "Jacuzzi": ["Jacuzzi"],
    "Jaguar (Animal)\fJeans": ["Jaguar (Animal)\fJeans"],
    "Jellyfish": ["Jellyfish", "Portuguese man-of-war", "man-of-war", "jellyfish"],
    "Jet ski": ["Jet ski"],
    "Jug": ["Jug", "jug", "jugful", "imprison", "incarcerate", "lag", "immure", "put behind bars", "jail", "gaol", "put away", "remand"],
    "Juice": ["Juice", "juice", "succus"],
    "Kangaroo": ["Kangaroo", "kangaroo"],
    "Kettle": ["Kettle", "kettle", "boiler", "kettleful", "kettle hole", "kettledrum", "tympanum", "tympani", "timpani"],
    "Kitchen & dining room table": ["Kitchen & dining room table"],
    "Kite": ["Kite", "kite"],
    "Koala": ["Koala", "koala", "koala bear", "kangaroo bear", "native bear", "Phascolarctos cinereus"],
    "Ladder": ["Ladder", "ladder", "run", "ravel"],
    "Ladle": ["Ladle", "ladle", "lade", "laden"],
    "Ladybug": ["Ladybug", "ladybug", "ladybeetle", "lady beetle", "ladybird", "ladybird beetle"],
    "Lamp": ["Lamp", "lamp"],
    "Lantern": ["Lantern", "lantern"],
    "Laptop": ["Laptop", "laptop", "laptop computer"],
    "Lavender (Plant)": ["Lavender (Plant)"],
    "Leg": ["Leg", "leg", "branch", "ramification", "peg", "wooden leg", "pegleg", "stage"],
    "Lemon": ["Lemon", "lemon", "gamboge", "lemon yellow", "maize", "lemon tree", "Citrus limon", "stinker"],
    "Leopard": ["Leopard", "leopard", "Panthera pardus"],
    "Light bulb": ["Light bulb"],
    "Light switch": ["Light switch"],
    "Lighthouse": ["Lighthouse", "beacon", "lighthouse", "beacon light", "pharos"],
    "Lily": ["Lily", "lily"],
    "Limousine": ["Limousine", "limousine", "limo"],
    "Lion": ["Lion", "lion", "king of beasts", "Panthera leo", "social lion", "Leo", "Leo the Lion"],
    "Lipstick": ["Lipstick", "lipstick", "lip rouge"],
    "Lizard": ["Lizard", "lizard", "lounge lizard"],
    "Lobster": ["Lobster", "lobster"],
    "Loveseat": ["Loveseat", "love seat", "loveseat", "tete-a-tete", "vis-a-vis"],
    "Luggage and bags": ["Luggage and bags"],
    "Lynx": ["Lynx", "lynx", "catamount"],
    "Magpie": ["Magpie", "magpie", "scavenger", "pack rat", "chatterer", "babbler", "prater", "chatterbox", "spouter"],
    "Mango": ["Mango", "mango", "mango tree", "Mangifera indica"],
    "Maple\fMaracas": ["Maple\fMaracas"],
    "Measuring cup": ["Measuring cup"],
    "Mechanical fan": ["Mechanical fan"],
    "Microphone": ["Microphone", "microphone", "mike"],
    "Microwave oven": ["Microwave oven"],
    "Milk": ["Milk", "milk", "Milk River"],
    "Miniskirt": ["Miniskirt", "miniskirt", "mini"],
    "Mirror": ["Mirror", "mirror"],
    "Mixer": ["Mixer", "sociable", "social", "mixer"],
    "Mixing bowl": ["Mixing bowl"],
    "Mobile phone": ["Mobile phone"],
    "Monkey": ["Monkey", "monkey", "imp", "scamp", "rascal", "rapscallion", "scalawag", "scallywag", "tamper", "fiddle", "putter", "mess around", "potter", "tinker", "monkey around", "muck about", "muck around"],
    "Moths and butterflies": ["Moths and butterflies"],
    "Motorcycle": ["Motorcycle", "motorcycle", "bike", "motorbike", "cycle"],
    "Mouse": ["Mouse", "mouse", "shiner", "black eye", "computer mouse", "sneak", "creep", "pussyfoot"],
    "Muffin": ["Muffin", "muffin", "gem"],
    "Mug": ["Mug", "mug", "mugful", "chump", "fool", "gull", "mark", "patsy", "fall guy", "sucker", "soft touch", "countenance", "physiognomy", "phiz", "visage", "kisser", "smiler"],
    "Mule": ["Mule", "mule", "scuff"],
    "Mushroom": ["Mushroom", "mushroom", "mushroom cloud", "mushroom-shaped cloud"],
    "Musical instrument": ["Musical instrument"],
    "Musical keyboard": ["Musical keyboard"],
    "Nail (Construction)": ["Nail (Construction)"],
    "Necklace": ["Necklace", "necklace"],
    "Nightstand": ["Nightstand"],
    "Oboe": ["Oboe", "oboe", "hautboy", "hautbois"],
    "Orange": ["Orange", "orange", "orangeness", "orange tree", "Orange River", "orangish"],
    "Ostrich": ["Ostrich", "ostrich", "Struthio camelus"],
    "Otter": ["Otter", "otter"],
    "Oven": ["Oven", "oven"],
    "Owl": ["Owl", "owl", "bird of Minerva", "bird of night", "hooter"],
    "Oyster": ["Oyster", "oyster", "huitre"],
    "Paddle": ["Paddle", "paddle", "boat paddle", "dabble", "splash around", "toddle", "coggle", "totter", "dodder", "waddle", "spank", "larrup"],
    "Palm tree": ["Palm tree"],
    "Pancake\fPanda": ["Pancake\fPanda"],
    "Paper cutter": ["Paper cutter"],
    "Paper towel": ["Paper towel"],
    "Parachute": ["Parachute", "parachute", "chute", "jump"],
    "Parking meter": ["Parking meter"],
    "Parrot": ["Parrot", "parrot"],
    "Pasta": ["Pasta", "pasta", "alimentary paste"],
    "Pastry": ["Pastry", "pastry", "pastry dough"],
    "Peach": ["Peach", "peach", "peach tree", "Prunus persica", "smasher", "stunner", "knockout", "beauty", "ravisher", "sweetheart", "lulu", "looker", "mantrap", "dish", "yellowish pink", "apricot", "salmon pink", "spill the beans", "let the cat out of the bag", "talk", "tattle", "blab", "babble", "sing", "babble out", "blab out"],
    "Pear": ["Pear", "pear", "pear tree", "Pyrus communis"],
    "Pen": ["Pen", "pen", "playpen", "penitentiary", "write", "compose", "indite"],
    "Pencil case": ["Pencil case"],
    "Pencil sharpener": ["Pencil sharpener"],
    "Penguin": ["Penguin", "penguin"],
    "Perfume": ["Perfume", "aroma", "fragrance", "perfume", "scent", "essence", "aromatize", "aromatise"],
    "Personal flotation device": ["Personal flotation device"],
    "Piano": ["Piano", "piano", "pianoforte", "forte-piano", "pianissimo", "soft", "softly"],
    "Picnic basket": ["Picnic basket"],
    "Picture frame": ["Picture frame"],
    "Pig": ["Pig", "hog", "pig", "grunter", "squealer", "Sus scrofa", "slob", "sloven", "slovenly person", "bull", "cop", "copper", "fuzz", "pig bed", "pig it", "devour", "guttle", "raven", "farrow"],
    "Pillow": ["Pillow", "pillow", "rest"],
    "Pineapple": ["Pineapple", "pineapple", "pineapple plant", "Ananas comosus", "ananas"],
    "Pitcher (Container)": ["Pitcher (Container)"],
    "Pizza": ["Pizza", "pizza", "pizza pie"],
    "Pizza cutter": ["Pizza cutter"],
    "Plastic bag": ["Plastic bag"],
    "Plate": ["Plate", "home plate", "home base", "home", "plate", "plateful", "crustal plate", "photographic plate", "collection plate", "scale", "shell", "denture", "dental plate"],
    "Platter": ["Platter", "platter", "phonograph record", "phonograph recording", "record", "disk", "disc"],
    "Polar bear": ["Polar bear"],
    "Pomegranate": ["Pomegranate", "pomegranate", "pomegranate tree", "Punica granatum"],
    "Popcorn": ["Popcorn", "popcorn", "Zea mays everta"],
    "Porch": ["Porch", "porch"],
    "Porcupine": ["Porcupine", "porcupine", "hedgehog"],
    "Poster": ["Poster", "poster", "posting", "placard", "notice", "bill", "card", "bill poster", "bill sticker", "post horse", "post-horse"],
    "Potato\fPower plugs and sockets": ["Potato\fPower plugs and sockets"],
    "Pressure cooker": ["Pressure cooker"],
    "Pretzel": ["Pretzel", "pretzel"],
    "Printer": ["Printer", "printer", "pressman", "printing machine"],
    "Pumpkin": ["Pumpkin", "pumpkin", "pumpkin vine", "autumn pumpkin", "Cucurbita pepo"],
    "Punching bag": ["Punching bag"],
    "Rabbit": ["Rabbit", "rabbit", "coney", "cony", "lapin", "hare"],
    "Raccoon": ["Raccoon", "raccoon", "racoon"],
    "Racket": ["Racket", "racket", "fraudulent scheme", "illegitimate enterprise", "noise", "dissonance", "racquet", "revel", "make whoopie", "make merry", "make happy", "whoop it up", "jollify", "wassail"],
    "Radish": ["Radish", "radish", "daikon", "Japanese radish", "Raphanus sativus longipinnatus", "Raphanus sativus", "radish plant"],
    "Ratchet (Device)": ["Ratchet (Device)"],
    "Raven": ["Raven", "raven", "Corvus corax", "prey", "predate", "devour", "guttle", "pig"],
    "Rays and skates": ["Rays and skates"],
    "Red panda": ["Red panda"],
    "Refrigerator": ["Refrigerator", "refrigerator", "icebox"],
    "Remote control": ["Remote control"],
    "Reptile": ["Reptile", "reptile", "reptilian"],
    "Rhinoceros": ["Rhinoceros", "rhinoceros", "rhino"],
    "Ring binder": ["Ring binder"],
    "Rocket": ["Rocket", "rocket", "projectile", "rocket engine", "roquette", "garden rocket", "rocket salad", "arugula", "Eruca sativa", "Eruca vesicaria sativa", "skyrocket"],
    "Roller skates": ["Roller skates"],
    "Rose": ["Rose", "rose", "rosebush", "blush wine", "pink wine", "rose wine", "rosiness", "rise", "lift", "arise", "move up", "go up", "come up", "uprise", "climb", "get up", "stand up", "rear", "surface", "rise up", "originate", "develop", "spring up", "grow", "ascend", "wax", "mount", "heighten", "turn out", "jump", "climb up", "rebel", "prove", "resurrect", "roseate", "rosaceous"],
    "Rugby ball": ["Rugby ball"],
    "Ruler": ["Ruler", "ruler", "swayer", "rule"],
    "Salad": ["Salad", "salad"],
    "Salt and pepper shakers": ["Salt and pepper shakers"],
    "Sandal": ["Sandal", "sandal"],
    "Sandwich": ["Sandwich", "sandwich"],
    "Saucer": ["Saucer", "disk", "disc", "saucer", "dish", "dish aerial", "dish antenna", "discus"],
    "Saxophone": ["Saxophone", "sax", "saxophone"],
    "Scale": ["Scale", "scale", "scale of measurement", "graduated table", "ordered series", "scale leaf", "scurf", "exfoliation", "musical scale", "weighing machine", "plate", "shell", "surmount", "descale"],
    "Scarf": ["Scarf", "scarf", "scarf joint"],
    "Scissors": ["Scissors", "scissors", "pair of scissors", "scissors hold", "scissor hold", "scissor grip", "scissors grip", "scissor"],
    "Scoreboard\fScorpion": ["Scoreboard\fScorpion"],
    "Screwdriver": ["Screwdriver", "screwdriver"],
    "Sculpture": ["Sculpture", "sculpture", "carving", "sculpt", "grave"],
    "Sea lion": ["Sea lion"],
    "Sea turtle": ["Sea turtle"],
    "Seafood": ["Seafood", "seafood"],
    "Seahorse": ["Seahorse", "walrus", "seahorse", "sea horse"],
    "Seal (Animal)": ["Seal (Animal)"],
    "Segway": ["Segway", "Segway Human Transporter", "Segway HT"],
    "Serving tray": ["Serving tray"],
    "Sewing machine": ["Sewing machine"],
    "Shark": ["Shark", "shark"],
    "Sheep": ["Sheep", "sheep"],
    "Shelf": ["Shelf", "shelf", "ledge"],
    "Shellfish": ["Shellfish", "shellfish", "mollusk", "mollusc"],
    "Shirt": ["Shirt", "shirt"],
    "Shorts": ["Shorts", "short pants", "shorts", "trunks", "drawers", "underdrawers", "boxers", "boxershorts", "short", "short circuit", "shortstop", "short-change", "short-circuit"],
    "Shower": ["Shower", "shower", "shower bath", "rain shower", "cascade", "exhibitor", "exhibitioner", "lavish", "shower down"],
    "Shrimp": ["Shrimp", "runt", "shrimp", "peewee", "half-pint", "prawn"],
    "Sink": ["Sink", "sink", "sinkhole", "swallow hole", "cesspool", "cesspit", "sump", "drop", "drop down", "pass", "lapse", "settle", "go down", "go under", "subside", "dip", "slump", "fall off", "slide down", "bury"],
    "Skateboard": ["Skateboard", "skateboard"],
    "Ski": ["Ski", "ski"],
    "Skirt": ["Skirt", "skirt", "annulus", "dame", "doll", "wench", "chick", "bird", "hedge", "fudge", "evade", "put off", "circumvent", "parry", "elude", "dodge", "duck", "sidestep", "surround", "environ", "ring", "border"],
    "Skunk": ["Skunk", "rotter", "dirty dog", "rat", "skunk", "stinker", "stinkpot", "bum", "puke", "crumb", "lowlife", "scum bag", "so-and-so", "git", "shutout", "pot", "grass", "green goddess", "dope", "weed", "gage", "sess", "sens", "smoke", "locoweed", "Mary Jane", "polecat", "wood pussy", "lurch"],
    "Skyscraper": ["Skyscraper", "skyscraper"],
    "Slow cooker": ["Slow cooker"],
    "Snail": ["Snail", "snail", "escargot"],
    "Snake": ["Snake", "snake", "serpent", "ophidian", "snake in the grass", "Snake River", "Hydra"],
    "Snowboard": ["Snowboard", "snowboard"],
    "Snowman": ["Snowman", "snowman"],
    "Snowmobile": ["Snowmobile", "snowmobile"],
    "Snowplow": ["Snowplow", "snowplow", "snowplough"],
    "Soap dispenser": ["Soap dispenser"],
    "Sock\fSofa bed": ["Sock\fSofa bed"],
    "Sombrero": ["Sombrero", "sombrero"],
    "Sparrow": ["Sparrow", "sparrow", "true sparrow", "hedge sparrow", "dunnock", "Prunella modularis"],
    "Spatula": ["Spatula", "spatula"],
    "Spice rack": ["Spice rack"],
    "Spider": ["Spider", "spider", "wanderer"],
    "Spoon": ["Spoon", "spoon", "spoonful", "smooch"],
    "Sports uniform": ["Sports uniform"],
    "Squash (Plant)": ["Squash (Plant)"],
    "Squid": ["Squid", "squid", "calamari", "calamary"],
    "Squirrel": ["Squirrel", "squirrel"],
    "Stairs": ["Stairs", "stairs", "steps", "step", "stair"],
    "Stapler": ["Stapler", "stapler", "stapling machine"],
    "Starfish": ["Starfish", "starfish", "sea star"],
    "Stationary bicycle": ["Stationary bicycle"],
    "Stool": ["Stool", "stool", "fecal matter", "faecal matter", "feces", "faeces", "BM", "ordure", "dejection", "toilet", "can", "commode", "crapper", "pot", "potty", "throne", "tiller", "defecate", "shit", "take a shit", "take a crap", "ca-ca", "crap", "make"],
    "Stop sign": ["Stop sign"],
    "Strawberry": ["Strawberry", "strawberry", "strawberry mark", "hemangioma simplex"],
    "Street light": ["Street light"],
    "Studio couch": ["Studio couch"],
    "Submarine": ["Submarine", "submarine", "pigboat", "sub", "U-boat", "bomber", "grinder", "hero", "hero sandwich", "hoagie", "hoagy", "Cuban sandwich", "Italian sandwich", "poor boy", "submarine sandwich", "torpedo", "wedge", "zep", "undersea"],
    "Submarine sandwich": ["Submarine sandwich"],
    "Suit": ["Suit", "suit", "suit of clothes", "lawsuit", "case", "cause", "causa", "courtship", "wooing", "courting", "accommodate", "fit", "befit", "beseem", "become"],
    "Suitcase": ["Suitcase", "bag", "traveling bag", "travelling bag", "grip", "suitcase"],
    "Sun hat": ["Sun hat"],
    "Sunglasses": ["Sunglasses", "sunglasses", "dark glasses", "shades", "sunglass"],
    "Surfboard": ["Surfboard", "surfboard", "surf"],
    "Sushi": ["Sushi", "sushi"],
    "Swan": ["Swan", "swan", "vagabond"],
    "Swim cap": ["Swim cap"],
    "Swimwear": ["Swimwear", "swimsuit", "swimwear", "bathing suit", "swimming costume", "bathing costume"],
    "Table": ["Table", "table", "tabular array", "mesa", "board", "postpone", "prorogue", "hold over", "put over", "shelve", "set back", "defer", "remit", "put off", "tabularize", "tabularise", "tabulate"],
    "Table tennis racket": ["Table tennis racket"],
    "Tablet computer": ["Tablet computer"],
    "Taco": ["Taco", "greaser", "wetback", "taco"],
    "Tap": ["Tap", "pat", "rap", "tap", "strike", "water faucet", "water tap", "hydrant", "spigot", "wiretap", "dab", "tip", "exploit", "intercept", "bug", "knock", "pink", "tapdance", "solicit", "beg"],
    "Tart": ["Tart", "prostitute", "cocotte", "whore", "harlot", "bawd", "tart", "cyprian", "fancy woman", "working girl", "sporting lady", "lady of pleasure", "woman of the street", "lemony", "lemonlike", "sourish", "tangy", "sharp", "sharp-worded"],
    "Taxi": ["Taxi", "cab", "hack", "taxi", "taxicab"],
    "Tea": ["Tea", "tea", "afternoon tea", "teatime", "Camellia sinensis", "tea leaf"],
    "Teapot": ["Teapot", "teapot"],
    "Teddy bear": ["Teddy bear"],
    "Telephone": ["Telephone", "telephone", "phone", "telephone set", "telephony", "call", "call up", "ring"],
    "Television": ["Television", "television", "telecasting", "TV", "video", "television system", "television receiver", "television set", "tv", "tv set", "idiot box", "boob tube", "telly", "goggle box"],
    "Tennis ball": ["Tennis ball"],
    "Tennis racket": ["Tennis racket"],
    "Tent": ["Tent", "tent", "collapsible shelter", "camp", "encamp", "camp out", "bivouac"],
    "Tiara": ["Tiara", "tiara"],
    "Tick": ["Tick", "tick", "ticking", "check mark", "check", "click", "ticktock", "ticktack", "beat", "retick", "check off", "mark", "mark off", "tick off"],
    "Tie": ["Tie", "necktie", "tie", "affiliation", "association", "tie-up", "tie beam", "link", "linkup", "tie-in", "draw", "standoff", "railroad tie", "crosstie", "sleeper", "bind", "connect", "link up", "attach", "bond", "marry", "wed", "splice"],
    "Tiger": ["Tiger", "tiger", "Panthera tigris"],
    "Tin can": ["Tin can"],
    "Toaster": ["Toaster", "toaster", "wassailer"],
    "Toilet": ["Toilet", "toilet", "lavatory", "lav", "can", "john", "privy", "bathroom", "commode", "crapper", "pot", "potty", "stool", "throne", "gutter", "sewer", "toilette"],
    "Toilet paper": ["Toilet paper"],
    "Tomato": ["Tomato", "tomato", "love apple", "tomato plant", "Lycopersicon esculentum"],
    "Toothbrush": ["Toothbrush", "toothbrush", "soup-strainer"],
    "Torch": ["Torch", "torch", "common mullein", "great mullein", "Aaron's rod", "flannel mullein", "woolly mullein", "Verbascum thapsus", "flashlight", "blowtorch", "blowlamp"],
    "Tortoise": ["Tortoise", "tortoise"],
    "Towel": ["Towel", "towel"],
    "Tower": ["Tower", "tower", "column", "pillar", "tugboat", "tug", "towboat", "loom", "predominate", "hulk"],
    "Toy": ["Toy", "plaything", "toy", "miniature", "toy dog", "dally", "play", "flirt", "fiddle", "diddle"],
    "Traffic light": ["Traffic light"],
    "Traffic sign": ["Traffic sign"],
    "Train": ["Train", "train", "railroad train", "string", "caravan", "wagon train", "gearing", "gear", "geartrain", "power train", "develop", "prepare", "educate", "discipline", "check", "condition", "groom", "school", "cultivate", "civilize", "civilise", "aim", "take", "take aim", "direct", "coach", "rail", "trail"],
    "Training bench": ["Training bench"],
    "Treadmill": ["Treadmill", "treadmill", "treadwheel", "tread-wheel", "salt mine"],
    "Tree": ["Tree", "tree", "tree"],
    "Tree house": ["Tree house"],
    "Tripod\fTrombone": ["Tripod\fTrombone"],
    "Trousers": ["Trousers", "trouser", "pant"],
    "Truck": ["Truck", "truck", "motortruck", "hand truck"],
    "Trumpet": ["Trumpet", "cornet", "horn", "trumpet", "trump"],
    "Turkey": ["Turkey", "turkey", "Meleagris gallopavo", "Republic of Turkey", "joker", "bomb", "dud"],
    "Turtle": ["Turtle", "turtleneck", "turtle", "polo-neck", "capsize", "turn turtle"],
    "Umbrella": ["Umbrella", "umbrella"],
    "Unicycle": ["Unicycle", "unicycle", "monocycle"],
    "Van": ["Van", "avant-garde", "vanguard", "van", "new wave", "caravan"],
    "Vase": ["Vase", "vase"],
    "Vegetable": ["Vegetable", "vegetable", "veggie", "veg"],
    "Violin": ["Violin", "violin", "fiddle"],
    "Volleyball (Ball)": ["Volleyball (Ball)"],
    "Waffle": ["Waffle", "waffle", "hesitate", "waver"],
    "Waffle iron": ["Waffle iron"],
    "Wall clock": ["Wall clock"],
    "Wardrobe": ["Wardrobe", "wardrobe", "closet", "press"],
    "Washing machine": ["Washing machine"],
    "Waste container": ["Waste container"],
    "Watch": ["Watch", "watch", "ticker", "vigil", "lookout", "lookout man", "sentinel", "sentry", "spotter", "scout", "picket", "observe", "follow", "watch over", "keep an eye on", "view", "see", "catch", "take in", "look on", "look out", "watch out", "determine", "check", "find out", "ascertain", "learn"],
    "Watercraft": ["Watercraft", "watercraft", "vessel"],
    "Watermelon": ["Watermelon", "watermelon", "watermelon vine", "Citrullus vulgaris"],
    "Whale": ["Whale", "giant", "hulk", "heavyweight", "whale"],
    "Wheel": ["Wheel", "wheel", "steering wheel", "roulette wheel", "rack", "bicycle", "bike", "cycle", "wheel around", "roll", "pedal"],
    "Whisk": ["Whisk", "whisk", "whisk broom", "whisk off", "whip"],
    "Whiteboard": ["Whiteboard"],
    "Willow": ["Willow", "willow", "willow tree"],
    "Window": ["Window", "window", "windowpane"],
    "Window blind": ["Window blind"],
    "Winter melon": ["Winter melon"],
    "Wok": ["Wok", "wok"],
    "Wood-burning stove": ["Wood-burning stove"],
    "Woodpecker": ["Woodpecker", "woodpecker", "peckerwood", "pecker"],
    "Worm\fWrench": ["Worm\fWrench"],
    "Zebra": ["Zebra", "zebra"],
    "Zucchini": ["Zucchini", "zucchini", "courgette"],
    "": [""],
    "Airfield": ["Airfield", "airfield", "landing field", "flying field", "field"],
    "Alley": ["Alley", "alley", "alleyway", "back street", "bowling alley", "skittle alley"],
    "Amusement Park": ["Amusement Park"],
    "Apartment Building": ["Apartment Building"],
    "Aquarium": ["Aquarium", "aquarium", "fish tank", "marine museum"],
    "Arcade": ["Arcade", "arcade", "colonnade"],
    "Art Studio": ["Art Studio"],
    "Automotive Repair": ["Automotive Repair"],
    "Ballroom": ["Ballroom", "ballroom", "dance hall", "dance palace"],
    "Bamboo": ["Bamboo", "bamboo"],
    "Bar": ["Bar", "barroom", "bar", "saloon", "ginmill", "taproom", "measure", "prevention", "legal profession", "legal community", "stripe", "streak", "cake", "Browning automatic rifle", "BAR", "debar", "exclude", "barricade", "block", "blockade", "stop", "block off", "block up", "banish", "relegate"],
    "Barn": ["Barn", "barn", "b"],
    "Baseball Field": ["Baseball Field"],
    "Basketball Court": ["Basketball Court"],
    "Beach": ["Beach", "beach"],
    "Beauty Salon": ["Beauty Salon"],
    "Boardwalk": ["Boardwalk", "boardwalk"],
    "Botanical Garden": ["Botanical Garden"],
    "Boxing Ring": ["Boxing Ring"],
    "Bridge": ["Bridge", "bridge", "span", "bridge circuit", "bridgework", "nosepiece", "bridge deck", "bridge over"],
    "Building": ["Building", "building", "edifice", "construction", "construct", "build", "make", "build up", "work up", "progress", "establish", "ramp up"],
    "Bullring": ["Bullring", "bullring"],
    "Bus Station": ["Bus Station"],
    "Cabin": ["Cabin", "cabin"],
    "Campsite": ["Campsite", "campsite", "campground", "camping site", "camping ground", "bivouac", "encampment", "camping area"],
    "Candy Store": ["Candy Store"],
    "Canyon": ["Canyon", "canyon", "canon"],
    "Car (Interior)\fCockpit": ["Car (Interior)\fCockpit"],
    "Coffee Shop": ["Coffee Shop"],
    "Computer Room": ["Computer Room"],
    "Conference Center": ["Conference Center"],
    "Corral": ["Corral", "cow pen", "cattle pen", "corral"],
    "Cottage": ["Cottage", "bungalow", "cottage"],
    "Desert": ["Desert", "desert", "abandon", "forsake", "desolate", "defect"],
    "Dining Hall": ["Dining Hall"],
    "Downtown": ["Downtown", "business district", "downtown"],
    "Drugstore": ["Drugstore", "drugstore", "apothecary's shop", "chemist's", "chemist's shop", "pharmacy"],
    "Escalator": ["Escalator", "escalator clause", "escalator", "moving staircase", "moving stairway"],
    "Excavation": ["Excavation", "excavation", "digging", "dig", "archeological site", "mining"],
    "Expo Booth": ["Expo Booth"],
    "Fabric Store": ["Fabric Store"],
    "Farm": ["Farm", "farm", "grow", "raise", "produce"],
    "Fire Station": ["Fire Station"],
    "Florist Shop": ["Florist Shop"],
    "Food Court": ["Food Court"],
    "Football Field": ["Football Field"],
    "Forest": ["Forest", "forest", "wood", "woods", "woodland", "timberland", "timber", "afforest"],
    "Garage": ["Garage", "garage", "service department"],
    "Garden": ["Garden", "garden"],
    "Gas Station": ["Gas Station"],
    "Glacier": ["Glacier", "glacier"],
    "Gym": ["Gym", "gymnasium", "gym"],
    "Hangar (Indoor)": ["Hangar (Indoor)"],
    "Harbor": ["Harbor", "seaport", "haven", "harbor", "harbour", "hold", "entertain", "nurse", "shield"],
    "Heliport": ["Heliport", "heliport"],
    "Highway": ["Highway", "highway", "main road"],
    "Home Theater": ["Home Theater"],
    "Ice Cream Parlor": ["Ice Cream Parlor"],
    "Ice Rink": ["Ice Rink"],
    "Iceberg\fJewelry Shop": ["Iceberg\fJewelry Shop"],
    "Kitchen": ["Kitchen", "kitchen"],
    "Laboratory": ["Laboratory", "lab", "laboratory", "research lab", "research laboratory", "science lab", "science laboratory", "testing ground"],
    "Lake": ["Lake", "lake"],
    "Laundromat": ["Laundromat", "launderette"],
    "Library": ["Library", "library", "depository library", "program library", "subroutine library"],
    "Living room": ["Living room"],
    "Lobby": ["Lobby", "anteroom", "antechamber", "entrance hall", "hall", "foyer", "lobby", "vestibule", "pressure group", "third house", "buttonhole"],
    "Market (Indoor)": ["Market (Indoor)"],
    "Market (Outdoor)": ["Market (Outdoor)"],
    "Mountain": ["Mountain", "mountain", "mount", "batch", "deal", "flock", "good deal", "great deal", "hatful", "heap", "lot", "mass", "mess", "mickle", "mint", "muckle", "passel", "peck", "pile", "plenty", "pot", "quite a little", "raft", "sight", "slew", "spate", "stack", "tidy sum", "wad"],
    "Movie Theater": ["Movie Theater"],
    "Museum": ["Museum", "museum"],
    "Neighborhood": ["Neighborhood", "vicinity", "locality", "neighborhood", "neighbourhood", "neck of the woods", "region"],
    "Nightclub": ["Nightclub", "cabaret", "nightclub", "night club", "club", "nightspot"],
    "Office": ["Office", "office", "business office", "agency", "federal agency", "government agency", "bureau", "authority", "function", "part", "role", "power", "office staff", "position", "post", "berth", "spot", "billet", "place", "situation"],
    "Orchard": ["Orchard", "grove", "woodlet", "orchard", "plantation"],
    "Pantry": ["Pantry", "pantry", "larder", "buttery"],
    "Park": ["Park", "park", "parkland", "commons", "common", "green", "ballpark", "Mungo Park", "parking lot", "car park", "parking area"],
    "Parking Lot": ["Parking Lot"],
    "Patio": ["Patio", "patio", "terrace"],
    "Performing Arts": ["Performing Arts"],
    "Pet Shop": ["Pet Shop"],
    "Phone Booth": ["Phone Booth"],
    "Pizzeria": ["Pizzeria", "pizzeria", "pizza shop", "pizza parlor"],
    "Public Transit Interior": ["Public Transit Interior"],
    "Public Transit Station": ["Public Transit Station"],
    "Racetrack (Equestrian)": ["Racetrack (Equestrian)"],
    "Raceway (Automotive)": ["Raceway (Automotive)"],
    "Raft": ["Raft", "raft", "batch", "deal", "flock", "good deal", "great deal", "hatful", "heap", "lot", "mass", "mess", "mickle", "mint", "mountain", "muckle", "passel", "peck", "pile", "plenty", "pot", "quite a little", "sight", "slew", "spate", "stack", "tidy sum", "wad"],
    "Recreation Room": ["Recreation Room"],
    "Restaurant": ["Restaurant", "restaurant", "eating house", "eating place", "eatery"],
    "Restaurant Patio": ["Restaurant Patio"],
    "River": ["River", "river"],
    "Rope Bridge\fSki Slope": ["Rope Bridge\fSki Slope"],
    "Sky": ["Sky", "sky", "flip", "toss", "pitch"],
    "Snowfield": ["Snowfield", "snowfield"],
    "Soccer Field": ["Soccer Field"],
    "Staircase": ["Staircase", "stairway", "staircase"],
    "Street": ["Street", "street"],
    "Supermarket": ["Supermarket", "supermarket"],
    "Swimming Pool": ["Swimming Pool"],
    "Volleyball Court (Outdoor)": ["Volleyball Court (Outdoor)"],
    "Water Fall": ["Water Fall"],
    "Wind Farm": ["Wind Farm"],
    "Windmill": ["Windmill", "windmill", "aerogenerator", "wind generator"],
    "Yard": ["Yard", "yard", "pace", "grounds", "curtilage", "thousand", "one thousand", "1000", "M", "K", "chiliad", "G", "grand", "thou", "cubic yard", "railway yard", "railyard"],
    "Indoor": ["Indoor", "indoor"],
    "Outdoor": ["Outdoor", "outdoor", "out-of-door", "outside"]
}